app/src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use App\Service\ShoppingCartService;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=ProductImage::class, mappedBy="product", orphanRemoval=true)
     */
    private $productImages;

    /**
     * @ORM\ManyToOne(targetEntity=Brand::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $brand;

    /**
     * @ORM\ManyToOne(targetEntity=Currency::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $currency;

    private int $shoppingCartQuantity = 0;

    public function __construct()
    {
        $this->productImages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|ProductImage[]
     */
    public function getProductImages(): Collection
    {
        return $this->productImages;
    }

    /**
     * @return ProductImage|null
     */
    public function getMainProductImage(): ?ProductImage
    {
        foreach ($this->getProductImages() as $productImage) {
            return $productImage;
        }

        return null;
    }

    public function addProductImage(ProductImage $productImage): self
    {
        if (!$this->productImages->contains($productImage)) {
            $this->productImages[] = $productImage;
            $productImage->setProduct($this);
        }

        return $this;
    }

    public function removeProductImage(ProductImage $productImage): self
    {
        if ($this->productImages->removeElement($productImage)) {
            // set the owning side to null (unless already changed)
            if ($productImage->getProduct() === $this) {
                $productImage->setProduct(null);
            }
        }

        return $this;
    }

    public function getBrand(): ?Brand
    {
        return $this->brand;
    }

    public function setBrand(?Brand $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getCurrency(): ?Currency
    {
        return $this->currency;
    }

    public function setCurrency(?Currency $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    public function getPriceWithoutVat(): string
    {
        return number_format($this->getPrice() / ShoppingCartService::DEFAULT_VAT, 2, '.', '');
    }

    public function getVatValue(): string
    {
        return number_format($this->getPrice() - $this->getPriceWithoutVat(), 2, '.', '');
    }

    /**
     * @return int
     */
    public function getShoppingCartQuantity(): int
    {
        return $this->shoppingCartQuantity;
    }

    /**
     * @param int $shoppingCartQuantity
     */
    public function setShoppingCartQuantity(int $shoppingCartQuantity): void
    {
        $this->shoppingCartQuantity = $shoppingCartQuantity;
    }
}

app/src/Controller/ShoppingCartController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Entity\Product;
use App\Form\OrderType;
use App\Service\OrderService;
use App\Service\ShoppingCartService;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ShoppingCartController extends AbstractController
{
    private EntityManagerInterface $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    /**
     * @Route("/shopping_cart", name="shopping_cart")
     */
    public function index(
        ShoppingCartService $shoppingCartService,
        Request $request,
        OrderService $orderService
    ): Response
    {
        $order = $orderService->initNewOrder();
        $orderForm = $this->createForm(OrderType::class, $order);

        $orderForm->handleRequest($request);

        if ($orderForm->isSubmitted() && $orderForm->isValid()) {
            $order = $orderService->handleOrderForm($orderForm, $request);

            if ($order) {
                $paymentStatus = $orderService->handlePaymentMethod($order, $orderForm);

                if (!empty($paymentStatus['status'])) {
                    if (!empty($paymentStatus['redirect'])) {
                        return $this->redirect($paymentStatus['redirect']);
                    }
                }
            }

            return $this->redirectToRoute('shopping_cart_feedback');
        }

        return $this->render('site/shopping_cart/index.html.twig', [
            'products' => $shoppingCartService->getValidProducts(),
            'total' => $shoppingCartService->getTotal(),
            'orderForm' => $orderForm->createView()
        ]);
    }

    /**
     * @Route("/shopping_cart/feedback", name="shopping_cart_feedback")
     */
    public function shoppingCartFeedback(OrderService $orderService): Response
    {
        $latestOrderId = $orderService->getLatestOrderId();

        $order = null;

        if ($latestOrderId) {
            $order = $this->em->getRepository(Order::class)->find($latestOrderId);
        }

        return $this->render('site/shopping_cart/feedback.html.twig', [
            'order' => $order
        ]);
    }

    /**
     * @Route("/shopping_cart/save_product", name="shopping_cart_add_product", methods={"POST"})
     */
    public function shoppingCartSaveProduct(
        Request $request,
        ShoppingCartService $shoppingCartService
    ): RedirectResponse
    {
        $productId = (int)$request->request->get('product_id');
        $quantity = (int)$request->request->get('quantity');

        if (!$productId) {
            throw new Exception('Invalid product ID!');
        }

        $shoppingCartService->saveProduct($productId, $quantity);

        return $this->redirectToRoute('shopping_cart');
    }

    /**
     * @Route("/ajax/shopping_cart/save_quantity/{product}/{quantity}", name="save_product_quantity")
     */
    public function saveProductQuantity(
        Product $product,
        int $quantity,
        ShoppingCartService $shoppingCartService
    ): JsonResponse
    {
        $feedback = [];

        $feedback['data'] = $shoppingCartService->saveProduct($product->getId(), $quantity);

        $feedback['content'] = $this->renderView('site/shopping_cart/snippets/shopping_cart.html.twig', [
            'products' => $shoppingCartService->getValidProducts(),
            'total' => $shoppingCartService->getTotal()
        ]);

        return new JsonResponse($feedback);
    }
}

app/templates/site/shopping_cart/snippets/shopping_cart.html.twig
{% if products is empty %}
    <div class="alert alert-warning text-center">
        <h3>{{ 'shopping_cart.empty_title' | trans }}</h3>
        <p>{{ 'shopping_cart.empty_subtitle' | trans }}</p>

        <a href="{{ path('product_list') }}" class="btn btn-secondary m-3">
            {{ 'shopping_cart.continue_shopping' | trans }}
        </a>
    </div>
{% else %}
    <div class="row">
        <div class="col-lg-9">
            <div class="table-responsive">
                <table class="table products-table">
                    <thead>
                    <tr>
                        <th colspan="2">{{ 'Product' | trans }}</th>
                        <th>{{ 'Brand' | trans }}</th>
                        <th>{{ 'Quantity' | trans }}</th>
                        <th>{{ 'Price' | trans }}</th>
                        <th class="text-nowrap">{{ 'shopping_cart.price_without_vat' | trans }}</th>
                        <th class="text-nowrap">{{ 'shopping_cart.vat_value' | trans }}</th>
                    </tr>
                    </thead>

                    <tbody class="products">
                        {% for product in products %}
                            <tr>
                                <td>
                                    <img src="{{ asset('uploads/product_images/' ~ product.getMainProductImage.name) }}"
                                         alt="Product image" class="img-thumbnail"
                                    >
                                </td>
                                <td>
                                    <a href="{{ path('product', {'product': product.id}) }}"
                                       class="text-decoration-none product-name">{{ product.name }}</a>
                                </td>
                                <td>{{ product.brand.name }}</td>
                                <td>
                                    <ul class="quantity-input-wrapper list-inline m-0 text-nowrap">
                                        <input type="hidden" name="product_id" value="{{ product.id }}">


                                        <li class="list-inline-item">
                                            <span class="btn btn-success btn-minus">-</span>
                                        </li>

                                        <li class="list-inline-item">
                                            <input type="hidden" name="products[{{ product.id }}][price]"
                                                   value="{{ product.price }}">
                                            <input type="hidden" name="products[{{ product.id }}][currency]"
                                                   value="{{ product.currency.id }}">

                                            <input type="text" name="products[{{ product.id }}][quantity]"
                                                   value="{{ product.shoppingCartQuantity }}"
                                                   class="quantity-input badge bg-secondary"
                                            >
                                        </li>

                                        <li class="list-inline-item">
                                            <span class="btn btn-success btn-plus">+</span>
                                        </li>
                                    </ul>
                                </td>
                                <td class="text-nowrap">{{ product.price }} {{ product.currency.name }}</td>
                                <td class="text-nowrap">
                                    {{ product.priceWithoutVat }} {{ product.currency.name }}
                                </td>
                                <td class="text-nowrap">{{ product.vatValue }} {{ product.currency.name }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="col-lg-3">
            <div class="card total">
                <div class="card-header">{{ 'Total' | trans }}</div>

                <ul class="list-group list-group-flush text-end">
                    <li class="list-group-item px-2">
                        <span>{{ 'shopping_cart.products_cost' | trans }}:</span>
                        <span class="text-end">{{ total.products_cost }} {{ total.currency }}</span>
                    </li>

                    <li class="list-group-item px-2">
                        <span>{{ 'shopping_cart.products_cost_without_vat' | trans }}:</span>
                        <span class="text-end">{{ total.products_cost_without_vat }} {{ total.currency }}</span>
                    </li>

                    <li class="list-group-item px-2">
                        <span>{{ 'shopping_cart.vat_value' | trans }}:</span>
                        <span class="text-end">{{ total.vat_value }} {{ total.currency }}</span>
                    </li>

                    <li class="list-group-item px-2">
                        <span>{{ 'shopping_cart.delivery_cost' | trans }}:</span>
                        <span class="text-end">{{ total.delivery_cost }} {{ total.currency }}</span>
                    </li>

                    <li class="list-group-item px-2">
                        <span>{{ 'shopping_cart.total' | trans }}:</span>
                        <span class="text-end">{{ total.total }} {{ total.currency }}</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endif %}